version: '3.9'

services:
    mysql:
        container_name: mysql
        image: mysql
        restart: always
        build:
            context: ./MySql/
            dockerfile: Dockerfile
            target: base
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: mysql
        ports:
            - 3306:3306
        command: --init-file /data/application/init.sql
        expose:
            - 3306
        volumes:
            - ./MySql/init.sql:/data/application/init.sql
            - ./MySql/data:/var/lib/mysql
            - ./MySql/logs:/var/log/mysql
        networks:
            xarxa_interna:
                ipv4_address: 172.22.0.11
        hostname: mysql
        

    flask_app:
        tty: true
        container_name: flask_app
        depends_on: 
            - mysql
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:5000
        expose:
            - 80
        networks:
            xarxa_interna:
                ipv4_address: 172.22.0.22
        hostname: flask_app
        restart: always
        privileged: true #required for the gpio

networks:
    xarxa_interna:
        name: internalNet
        ipam:
            config:
                - subnet: '172.22.0.0/24'