version: '3.9'


services:
    mysql:
        container_name: mysql
        image: mysql
        restart: always
        build:
            context: ./MySql/
            dockerfile: Dockerfile
            target: base
        environment:
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: mysql
            FLASK_APP_IP: ${FLASK_APP_IP}
        command: ["/etc/mysql/init.sh"]
        volumes:
            - ./MySql/init.sql:/data/application/init.sql.template
            - ./MySql/data:/var/lib/mysql
            - ./MySql/logs:/var/log/mysql
        networks:
            xarxa_interna:
                ipv4_address: ${MYSQL_IP}
        hostname: mysql
         

    flask_app:
        tty: true
        container_name: flask_app
        depends_on: 
            - mysql
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
        expose:
            - 80
        networks:
            xarxa_interna:
                ipv4_address: ${FLASK_APP_IP}
        hostname: flask_app
        restart: always


   

networks:
    xarxa_interna:
        name: internalNet
        ipam:
            config:
                - subnet: '172.22.0.0/24'