version: '3.9'

services:
    mysql:
        container_name: mysql
        image: biarms/mysql:5.7.30
        restart: always
        build:
            context: ./MySql/
            dockerfile: Dockerfile
            target: base
        environment:
            MYSQL_DATABASE: mysql
            FLASK_APP_IP: ${FLASK_APP_IP}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./MySql/data:/var/lib/mysql
            - ./MySql/logs:/var/log/mysql
            - ./MySql/my.cnf:/config/my.cnf
        networks:
            xarxa_interna:
                ipv4_address: ${MYSQL_IP}
        hostname: mysql
         

    flask_app:
        restart: always
        container_name: flask_app
        depends_on: 
            - mysql
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        ports:
            - 80:80
            - 443:443   
        expose:
            - 80
            - 443
        networks:
            xarxa_interna:
                ipv4_address: ${FLASK_APP_IP}
        hostname: flask_app
        privileged: true

networks:
    xarxa_interna:
        name: internalNet
        ipam:
            config:
                - subnet: '172.22.0.0/24'