"""adding hashing in passwords

Revision ID: 401d06fa6964
Revises: cde58f5b17d6
Create Date: 2022-09-18 20:29:15.087425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '401d06fa6964'
down_revision = 'cde58f5b17d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=40), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
