"""remove username

Revision ID: 98906f9ebd4b
Revises: 50b8f46b7b21
Create Date: 2023-04-24 23:10:28.854336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98906f9ebd4b'
down_revision = '50b8f46b7b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=30), nullable=False))
    op.create_index('username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###
