"""Initial Migration

Revision ID: ae0a2732c094
Revises: e1f55fc2698b
Create Date: 2023-05-26 22:52:15.721958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae0a2732c094'
down_revision = 'e1f55fc2698b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relay', sa.Column('_id', sa.Integer(), nullable=False))
    op.add_column('relay', sa.Column('_state', sa.Boolean(), nullable=False))
    op.add_column('relay', sa.Column('_DateTime', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'relay', ['_id'])
    op.drop_column('relay', 'state')
    op.drop_column('relay', 'DateTime')
    op.drop_column('relay', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relay', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('relay', sa.Column('DateTime', mysql.DATETIME(), nullable=False))
    op.add_column('relay', sa.Column('state', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'relay', type_='unique')
    op.drop_column('relay', '_DateTime')
    op.drop_column('relay', '_state')
    op.drop_column('relay', '_id')
    # ### end Alembic commands ###
