"""empty message

Revision ID: e1f55fc2698b
Revises: dfb87e236f6f
Create Date: 2023-05-01 15:19:02.793539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1f55fc2698b'
down_revision = 'dfb87e236f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_index('role', table_name='roles')
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'roles', ['name'])
    op.drop_column('roles', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('role', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_index('role', 'roles', ['role'], unique=False)
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###
